<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Zend Framework</span></h1>

</div>
<div class="row">
    <a href="<?php echo $this->basePath('/post/add') ?> " class="btn btn-primary">CREATE</a>
    <!-- <div class="input-group col-sm-6 pull-right">
        <input type="text" name="search_keyword" value="<?= $this->searchKeyword ?>" class="form-control rounded" placeholder="Search" aria-label="Search..." aria-describedby="search-addon" />
        <button type="button" class="btn btn-outline-primary" type="submit">search</button>
    </div> -->
<!-- </div> -->

<div class="col-sm-6 pull-right ">
        <form method="get">
            <div class="input-group pull-right">
            <input name="search_keyword" type="text" class="form-control" placeholder="Search..." value="<?= $this->searchKeyword ?>">
                <span class="input-group-btn">
                    <button class="btn btn-outline-primary" type="submit">Search
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </div>
        </form>
</div>
</div>
<div class="row">
<table class="table table-hover">
  <thead>
    <tr>
        <th scope="col" ><a href="<?php echo $this->url('post',['action'=>'sort','column'=>'id'], ['query' => ['page' =>$this->page,'search_keyword' => $this->searchKeyword,
            'sort' => 'id','sort_by' => $this->sort_by]]) ?>" class="sort">ID</a></th>
        <th scope="col" ><a href="<?php echo $this->url('post',['action'=>'sort','column'=>'id'], ['query' => ['page' =>$this->page,'search_keyword' => $this->searchKeyword,
            'sort' => 'title','sort_by' => $this->sort_by]]) ?>" class="sort">Title</a></th>
        <th scope="col" ><a href="<?php echo $this->url('post',['action'=>'sort','column'=>'id'], ['query' => ['page' =>$this->page,'search_keyword' => $this->searchKeyword,
            'sort' => 'description','sort_by' => $this->sort_by]]) ?>" class="sort">Description</a></th>
        <th scope="col" ><a href="<?php echo $this->url('post',['action'=>'sort','column'=>'id'], ['query' => ['page' =>$this->page,'search_keyword' => $this->searchKeyword,
            'sort' => 'category','sort_by' => $this->sort_by]]) ?>" class="sort">Category</a></th>
      <th scope="col">Action</th>

    </tr>
  </thead>
  <tbody>
      <?php if(count($this->paginator)>0):?>
          <?php foreach($this->paginator as $post):?>
        <tr>
            <th><?php echo $post->getId();?></th>
            <td><?php echo $post->getTitle();?></td>
            <td><?php echo $post->getDescription();?></td>
            <td><?php echo $post->getCategory();?></td>
            <td><a href="<?php echo $this->url('post',['action'=>'view','id'=>$post->getId()]) ?>" class="btn btn-primary">VIEW</a></td>
            <td><a href="<?php echo $this->url('post',['action'=>'edit','id'=>$post->getId()]) ?>" class="btn btn-success">UPDATE</a></td>
            <td><a href="<?php echo $this->url('post',['action'=>'delete','id'=>$post->getId()]) ?>" class="btn btn-danger">DELETE</a></td>

        </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                 <td>No Records Found! </td>
            </tr>
        <?php endif; ?>
    
  </tbody>
</table>
<?= $this->paginationControl(
    // The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    ['page'=>$this->page,'searchKeyword' => $this->searchKeyword,'sort_by' => $this->sort_by,'sort'=>$this->sort],

    // The route to link to when a user clicks a control link:
    ['route' => 'post'],

) ?>
</div>

