<?php if ($this->pageCount): ?>
    <ul class="pagination pagination-sm">
        <?php if (!isset($this->previous)): ?>
            <li class="disabled">
                <a>«</a>
                <a>‹</a>
            </li>
        <?php else: ?>
            <li>
                <a href="<?= $this->url($this->route, [], 
                    ['query' => [
                        'page' => $this->first, 
                        'search_keyword' => $this->searchKeyword
                    ]]); ?>">«</a>
                <a href="<?= $this->url($this->route, [], 
                    ['query' => [
                        'page' => $this->previous, 
                        'search_keyword' => $this->searchKeyword
                    ]]); ?>">‹</a>
            </li>
        <?php endif; ?>
        
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page == $this->current): ?>
                <li class="active">
                    <a><?= $page ?></a>
                </li>
            <?php else: ?>
                <li>
                    <a href="<?= $this->url($this->route, [], 
                        ['query' => [
                            'page' => $page, 
                            'search_keyword' => $this->searchKeyword
                        ]]); ?>">
                        <?= $page; ?>
                    </a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    
        <?php if (!isset($this->next)): ?>
            <li class="disabled">
                <a>›</a>
                <a>»</a>
            </li>
        <?php else: ?>
            <li>
                <a href="<?= $this->url($this->route, [], 
                    ['query' => [
                        'page' => $this->next, 
                        'search_keyword' => $this->searchKeyword
                    ]]); ?>">›</a>
                <a href="<?= $this->url($this->route, [], 
                    ['query' => [
                        'page' => $this->last, 
                        'search_keyword' => $this->searchKeyword
                    ]]); ?>">»</a>
            </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>
